"use client";

import { Suspense, useCallback, useEffect, useRef, useState } from "react";
import { useSession } from "next-auth/react";
import { Shield, Loader2, CheckCircle2, AlertTriangle } from "lucide-react";
import { portalApi } from "@/lib/api";

/**
 * First-run device enrollment.
 *
 * An agent that has just been installed has no credentials — a notarized
 * package is identical for every employee, so it cannot ship any. It opens
 * this page instead and waits on loopback: the employee's portal session is
 * what proves whose device this is, and the browser carries the token the last
 * hop to the waiting agent.
 *
 * The `state` string is what makes that hop safe. It was generated by the
 * agent and put in the URL it opened, so quoting it back is how this page
 * proves it is the page that agent sent the employee to, rather than any other
 * tab that happens to know the port.
 */

type Phase = "checking" | "enrolling" | "done" | "error";

/**
 * Only ever POST to the local machine. `callback` arrives in a URL, so
 * treating it as trusted would turn this page into a way to have somebody's
 * browser hand a live enrollment token to an arbitrary host.
 */
function isLoopbackCallback(raw: string): boolean {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return false;
  }
  return (
    url.protocol === "http:" &&
    (url.hostname === "127.0.0.1" || url.hostname === "[::1]" || url.hostname === "::1")
  );
}

function EnrollFlow() {
  const { status } = useSession();
  const [phase, setPhase] = useState<Phase>("checking");
  const [message, setMessage] = useState("");
  // React re-runs effects in development's strict mode; enrolling twice would
  // register the same laptop as two devices.
  const started = useRef(false);

  const run = useCallback(async () => {
    const params = new URLSearchParams(window.location.search);
    const state = params.get("state") || "";
    const callback = params.get("callback") || "";

    if (!state || !callback) {
      setPhase("error");
      setMessage(
        "This page is opened automatically by the Aavishield agent during setup. " +
          "There is nothing to do here — you can close this tab."
      );
      return;
    }
    if (!isLoopbackCallback(callback)) {
      setPhase("error");
      setMessage("This enrollment link is not valid. Contact your IT administrator.");
      return;
    }

    setPhase("enrolling");
    let token: string;
    let adminUrl: string;
    try {
      const { data } = await portalApi.enrollDevice();
      token = data.token;
      adminUrl = data.admin_url;
    } catch {
      setPhase("error");
      setMessage("Could not create an enrollment code. Please try again in a moment.");
      return;
    }

    // The two failures below are genuinely different and used to collapse into
    // one message: an agent that answered with a reason is not an agent that
    // couldn't be reached. Telling someone whose device is simply already
    // registered to "make sure the agent is running" sends them to fix
    // something that was never broken.
    let res: Response;
    try {
      res = await fetch(callback, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ state, token, admin_url: adminUrl }),
      });
    } catch {
      setPhase("error");
      setMessage(
        "Could not reach the Aavishield agent on this device. Make sure it is " +
          "running, then reopen this page from the agent."
      );
      return;
    }

    if (!res.ok) {
      const detail = await res.json().catch(() => ({} as { error?: string }));
      setPhase("error");
      // The agent forwards the server's own wording — for an already-registered
      // device that's the line naming who can unblock it, which is the only
      // useful thing to show here.
      setMessage(detail?.error || `The agent could not complete setup (${res.status}).`);
      return;
    }

    setPhase("done");
  }, []);

  useEffect(() => {
    if (status === "loading" || started.current) return;
    if (status === "unauthenticated") {
      const target = window.location.pathname + window.location.search;
      window.location.href = `/login?callbackUrl=${encodeURIComponent(target)}`;
      return;
    }
    started.current = true;
    run();
  }, [status, run]);

  return (
    <div className="min-h-screen flex items-center justify-center bg-background px-4">
      <div className="w-full max-w-md bg-card border border-border rounded-2xl shadow-sm p-8 text-center">
        <div className="w-12 h-12 rounded-xl bg-brand-500/10 flex items-center justify-center mx-auto mb-5">
          <Shield className="w-6 h-6 text-brand-500" />
        </div>

        {(phase === "checking" || phase === "enrolling") && (
          <>
            <h1 className="text-lg font-semibold text-foreground">Setting up this device</h1>
            <p className="text-sm text-muted-foreground mt-2">
              Connecting the Aavishield agent to your account. This only takes a moment.
            </p>
            <Loader2 className="w-5 h-5 text-brand-500 animate-spin mx-auto mt-6" />
          </>
        )}

        {phase === "done" && (
          <>
            <CheckCircle2 className="w-8 h-8 text-success mx-auto mb-3" />
            <h1 className="text-lg font-semibold text-foreground">This device is protected</h1>
            <p className="text-sm text-muted-foreground mt-2">
              Setup is complete — nothing else to do. You can close this tab.
            </p>
            <a
              href="/dashboard"
              className="inline-block mt-6 text-sm text-brand-500 hover:text-brand-400"
            >
              Go to my dashboard
            </a>
          </>
        )}

        {phase === "error" && (
          <>
            <AlertTriangle className="w-8 h-8 text-amber-500 mx-auto mb-3" />
            <h1 className="text-lg font-semibold text-foreground">Setup could not finish</h1>
            <p className="text-sm text-muted-foreground mt-2">{message}</p>
          </>
        )}
      </div>
    </div>
  );
}

export default function EnrollPage() {
  return (
    <Suspense fallback={null}>
      <EnrollFlow />
    </Suspense>
  );
}
